### ISSUE TITLE
JDatabaseQuery clones $db Object

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-platform#1167]
Testing:
$query = JFactory::getDbo()->getQuery(true);
$clonedquery = clone $query;
$quotedstring = $clonedquery->q('string');

Ends in:
Warning: mysqli_real_escape_string(): Couldn't fetch mysqli in libraries/joomla/database/database/mysqli.php on line 157

I think cloning the $db Object in JDatabaseQuery is a bad Idea, so adding a exception for the database variable would be a solution.

**Comment by elinw** [comment]
https://github.com/joomla/joomla-platform/blob/staging/tests/suites/unit/joomla/database/JDatabaseQueryTest.php

Could you outline or propose a failing test that illustrates this problem? 

http://php.net/manual/en/mysqli.real-escape-string.php

I think the problem is probably not the clone, it's probably the handling of mysqli_escape_string versus mysql_escape_string (which are different see above kubj) but this requires some digging. 

P.S. obviously you are using 11.4 not the current platform but this part of he code has not changed although it has been moved around.
I think part of the problem is the error suppression here 
https://github.com/joomla/joomla-cms/blob/master/libraries/joomla/database/database/mysqli.php#L98
which is creating a red herring.

**Comment by elinw** [comment]
See also closed issue #238. 
Which session handler are you using?
