### ISSUE TITLE
/libraries/cms/form/field/user.php - frontend functionality

### ISSUE THREAD

**Issue by GazEdge** [joomla/joomla-platform#1515]
When editing frontend forms as the superuser where the form field is 'user' it is not possible to select a user from the modal window. Instead the superusers profile is shown.

One way to semi fix this is to change line 42 to:

$link = '/administrator/index.php?option=com_users&amp;view=users&amp;layout=modal&amp;tmpl=component&amp;field=' . $this->id

The only problem is now when the modal window pops up, it takes the user to the administrator log on page and consequently loads the modal page as a full page with no ability to select to correct user.

If the superuser is already logged in as administrator AND in the front end, the modal window behaves as expected on the frontend form, and a user can be selected.

Is there a way for the super user to be auto logged into the backend from the frontend?

**Comment by elinw** [comment]
This is actually from the CMS library so it needs to go into the CMS tracker, but it's an interesting question.   There are ways to do  an acl check on an admin view from the front end (we do that with the media manager).  You could also make a custom field that just does the query and its own pagination rather than use the core field. Overall I suspect the cms would welcome a pull request to cope with this scenario. I don't know if the platform would want  a user field that is not entangled with com_user or use a layout but personally I think it would pretty useful field in many web applications.

**Comment by realityking** [comment]
I'm closing this one since it's a bug in a CMS library.
