### ISSUE TITLE
pdo driver: $checkConnected is already true

### ISSUE THREAD

**Issue by tbela99** [joomla/joomla-platform#1545]
the line 537 is superfuous,

```
         if ($checkingConnected) { // checkingConnected is already true$checkingConnected = true;
        die('Recursion trying to check if connected.');
    }
```

https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/database/driver/pdo.php#L537

**Comment by pasamio** [comment]
Agree, put in a pull request to remove it.

**Comment by tbela99** [comment]
I have some kind of deadlock here when using oracle pdo driver. 
connected method calls query which in it turns which calls connected again somewhere in the call chain and finally die('Recursion trying to check if connected.');

**Comment by pasamio** [comment]
I've pondered for a while if in fact the better behaviour instead of the die is to just return false. What triggered this for me were deadlocks in Oracle which resulted in it terminating my connection abnormally I believe. Throwing an exception within there while we're trying to work it out results instead in an infinite loop but I haven't had it regularly recur to test what returning false would cause because if another exception is triggered we end up in an infinite loop again. Are you regularly hitting this die?

**Comment by tbela99** [comment]
Yes, I can't run any query. connected should run the query directly instead of calling query which leads to that infinite loop

**Comment by pasamio** [comment]
Well what it's trying to do is run the query to validate that the error it received was that it was disconnected versus some other form of exception that it can reasonably recover from and continue sending queries to the database engine.

**Comment by elinw** [comment]
@tbela99 You can go to the file here on github, click edit and make the proposed change (reference #1545 in the comment).
