### ISSUE TITLE
JHtmlBehavior::formvalidation()

### ISSUE THREAD

**Issue by piotrmocko** [joomla/joomla-platform#1546]
JavaScript form validation does not work because mootools-more is not loaded.

file:
libraries/joomla/html/behavior.php
method:
formvalidation()
change:
self::framework();
to:
self::framework(true);

Joomla 3.0 Beta 1

**Comment by dongilbert** [comment]
Mootools-more is not required for form validation to work in Joomla 2.5.x, so I'm not sure why they make that change, seeing that J!3 is more bent towards jQuery instead. I'll need to look into this more.

**Comment by piotrmocko** [comment]
It is required to use function isValid()
in file: media/system/js/validate.js
which is a Joomla! from validator.
This function use "Hash" which is part of mootools-more.
It was correct in Joomla 2.5 but in Joomla 3.0 Beta 1 mootools-more was removed from validator

**Comment by piotrmocko** [comment]
Please apply this update before releasing Joomla! 3.0 because my extension use this function from Joomla! validation script and it would not work

**Comment by dongilbert** [comment]
Is this an extension you have distributed? Or one you are working on for a client? If it's the latter, you can add the call to `JHtml::framework(true);` to your code, and will bring in the required js. If it's a distributed extension, I think you could get away with pushing another update that does the same thing I mentioned above, and call it a 3.0 compatibility update. If you're users are upgrading their site to 3.0, then I don't think they'll have an issue with upgrading an extension as well. Also, they are probably comfortable with code, and could be just as easily instructed to add the same code block to the template's index.php file.

I'm only giving these suggestions because I'm not sure if this can make it in on time, since 3.0 is scheduled for release tomorrow.

**Comment by mbabker** [comment]
Did Hash move between MooTools Core and More by chance?

**Comment by dongilbert** [comment]
Looks like Hash was always in More, but in J!2.5.x, there was a MooTools 1.2 compatibility in mt-core that provided some type of hash compatibility. See https://github.com/joomla/joomla-cms/blob/2.5.x/media/system/js/mootools-core-uncompressed.js#L412 - That compat section been removed in the 3.0 branch.

So, to answer the question, it hasn't moved, but the compatibility layer was removed.

**Comment by mbabker** [comment]
That removal was intended.  So if we need to ensure MT More is loaded for that, then this fix will work.  Care to do the pull request?

**Comment by piotrmocko** [comment]
I have better solution. I have upgraded Joomla! validation script to work without Hash.
I have wrote part of code which do the same as Hash - converts object to array.

...

```
isValid: function(form)
{
    var valid = true;

    // Validate form fields
    var elements = form.getElements('fieldset').concat(Array.from(form.elements));
    for (var i=0;i < elements.length; i++) {
        if (this.validate(elements[i]) == false) {
            valid = false;
        }
    }

    // Run custom form validators if present
    var customHandlers = [];
    for (var key in this.custom) {
        if (this.custom.hasOwnProperty(key)) {
          customHandlers.push(this.custom[key]);  
        }
    }
    customHandlers.each(function(validator){
        if (validator.exec() != true) {
            valid = false;
        }
    });

    return valid;
}
```

**Comment by dongilbert** [comment]
Pull request away - I like the that implementation since the validation script only requires that one simple feature of the Hash js. No need to load the full More library.

**Comment by piotrmocko** [comment]
By the way I have related improvement into validation script posted on
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=26114
Submitted By: Piotr Moćko
Adddate: 2012-02-28 11:46:24

**Comment by piotrmocko** [comment]
In Joomla 3.0.1 it was not updated. Should I do something with this topic?

**Comment by pasamio** [comment]
3.0.1 was primarily security and critical bug fixes around update work that needed to be done. It might get picked up in a later release if someone merges platform back down to the CMS after it gets fixed in the platform or alternatively you can push to get it fixed in the CMS. TBQH it sounds more like a CMS issue more than a platform issue.

**Comment by piotr-cz** [comment]
Since MooTools 1.3 most of Hash functions has been moved to [Object](http://mootools.net/docs/core/Types/Object#Deprecated-Functions) (which is part of Mootools Core) and documentation discourages using Hash class ([When possible, please use the Object type!](http://mootools.net/docs/more/Types/Hash)).

A while back [I refactored the Validator script](https://github.com/piotr-cz/joomla-platform/blob/JFormValidator/media/system/js/validate.js) to act as a wrapper to MooTools native [Form.Validator](http://mootools.net/docs/more/Forms/Form.Validator) and optionally use HTML5 validations.

The code is heavily commented, contains backward compatibility methods to current version of validator.js and is simpler.

**Comment by piotrmocko** [comment]
This code looks nice. I will have to test it. I think that it is high time to rebulid Joomla validation.

Check also if it would validate multiple select list as required

**Comment by piotr-cz** [comment]
This hasn't been tested much, just few forms on frontend and backend in joomla 2.5. 
The question howewer is JS framework. Code is tightly coupled to Mootools. 

[Description what I wanted to achieve](https://groups.google.com/group/joomla-dev-platform/tree/browse_frm/thread/40d272bbca1d6750/6662695e5b519c6a?rnum=11&_done=%2Fgroup%2Fjoomla-dev-platform%2Fbrowse_frm%2Fthread%2F40d272bbca1d6750%2F%3F#doc_c0e16031b44bb7ed)

**Comment by alonextou** [comment]
Why was this ignored for 3.0.1, pasamio's reason is not good, because this is a simple and mandatory feature in Joomla's core. My registration form's return no value's. Is there a fix or branch for this I could use?

**Comment by dongilbert** [comment]
You can edit the files for your site, and then when this get's merged into
core, you can drop your changes.

I wrote this up for overriding core Joomla classes with your own code -
https://gist.github.com/3237387

**Comment by alonextou** [comment]
Thanks dongilbert, the problem is I'm not too sure what I need to override, or what code I need to make it work. I was hoping someone who fixed this had a branch, or some code to copy. I'll give it a shot though.

**Comment by piotrmocko** [comment]
Add to your form temporary PHP code: 

```
self::framework(true);
```

to solve this issue. 

You might also override JavaScript class with isValid method by adding following code to your form JS file:

```
JFormValidator.implement({
isValid: function(form)
{
    var valid = true;

    // Validate form fields
    var elements = form.getElements('fieldset').concat(Array.from(form.elements));
    for (var i=0;i < elements.length; i++) {
        if (this.validate(elements[i]) == false) {
            valid = false;
        }
    }

    // Run custom form validators if present
    var customHandlers = [];
    for (var key in this.custom) {
        if (this.custom.hasOwnProperty(key)) {
          customHandlers.push(this.custom[key]);  
        }
    }
    customHandlers.each(function(validator){
        if (validator.exec() != true) {
            valid = false;
        }
    });

    return valid;
}
});
```

**Comment by alonextou** [comment]
Thanks piotrmocko, but I changed self::framework(); to self::framework(true); in libraries/joomla/html/behavior.php, method formvalidation(), but it made no difference.

I am only trying to fix the Joomla registration form here, which does not return any warnings or errors.

**Comment by piotr-cz** [comment]
@awc737:
I've tried [registration on Joomla demo](http://joomla30.cloudaccess.net/index.php/using-joomla/extensions/components/users-component/registration-form) and looks like validation passed fine, fields receive classname `invalid` but there's no css styling attached to it so user has no easy change to pick up what's wrong. Is this what you are after?

If no, maybe we should move the discussion to Google groups..

pasamino is right, there's kind of confusion with javascript supplied with the platform. If platform is to be as slim as possible, these assets should move to the CMS. Besides Joomla 3.0.x is running on Platform 12.2, but current platform version is tagged 12.3.

**Comment by alonextou** [comment]
On that demo piotr-cz, shouldn't clicking 'Register' with all fields blank, or all invalid fields, at least return some kind of message, like a tool tip response or something?

**Comment by pasamio** [comment]
If you click on the field it is highlighted red. Near as I can the field is tagged with the class "invalid" as is the label. The label also has an `aria-linvalid` true attribute as well. It would appear something is validating the field.

It is up to the template to decide how it wishes to render invalid fields. In this case the red highlighting doesn't occur unless you've clicked on the field. This is likely a bug in the CSS for the template that needs to be looked at so that it continues to highlight invalid fields that are not active. The template isn't something that the platform distributes but is in this case the CMS.

So as I noted before, I do not feel this is not a platform bug but a CMS bug. You're welcome to submit a pull request here to change that but we'll likely defer to the CMS folk as they're the ones most likely to be impacted by the change. However as I noted it doesn't mean it will immediately be available until the CMS chooses to pick it up from the Platform project.

Finally the Platform doesn't decide what goes in the CMS releases. The CMS is a downstream consumer of the Platform and as such we don't directly control what does or doesn't go into it's releases. While the CMS is certainly a source of fixes and improvements for the Platform, when it updates it's copy is on it's terms not ours. As I noted earlier the 3.0.1 release was a security release which the Joomla CMS typically stays away from making big changes in so that people aren't afraid that their site will be broken. This means only critical fixes and the security fixes usually go in. This is why something like this, apart from not even being fixed in the platform or a registered bug for the CMS, wasn't included or would be likely to be included.

**Comment by piotr-cz** [comment]
@awc737 In my opinion it should immediately change border-color of invalid fields to red, like it has been happening in previous Joomla versions (maybe that's something that has been overlooked?).

Anyway as pasamino suggests, this can't be fixed here as this is a template thing and platform is not being shipped with templates. Try to add an issue or pull request in the CMS tracker, I'm pretty sure that more people are annoyed with this behavior.

Quick fix could be to prepend `input.invalid, textarea.invalid, select.invalid,` in [template.css](https://github.com/joomla/joomla-cms/blob/master/templates/protostar/css/template.css#L1135) or if such behaviour works in the admin, replicate it for protostar template. Or check if/ how it's done for beez template.

We are discussing something quite different here: in some cases validator dependecies are not loaded/ how to make it lightweight.

Edit: [This commit](https://github.com/joomla/joomla-cms/commit/969496e32e41c661b38369d5a9fcd645c62054aa) probably fixed invalid input filelds styling
