### ISSUE TITLE
Stream Chunksize

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-platform#1562]
From libraries/joomla/filesystem/file.php, lines 379-380:

```
        // Beef up the chunk size to a meg
        $stream->set('chunksize', (1024 * 1024 * 1024));
```

Does anyone else see a problem with this?

**Comment by pasamio** [comment]
one too many 1024's

**Comment by okonomiyaki3000** [comment]
No, that's not it. 'gig' is misspelled.

**Comment by dongilbert** [comment]
Well, I think what was meant here was what the comment is saying. Since this is regarding writing files using streams, and by default the chunksize is set to 8KB, I think it's reasonable to assume that there are - as @pasamio said - one too many 1024's.

What we really need to do is ask the creator if he meant what he coded, or if he meant what he commented. This chunk of code was added here - https://github.com/joomla/joomla-platform/blob/a9bf5568433de1e4a6ee11c9ce1cbf3ceb0d6d25/joomla/filesystem/file.php#L300 - by @pasamio. And we already have his vote. So I'll send in a quick fix PR after making sure changing it doesn't break any unit tests.

**Comment by elinw** [comment]
This can be closed
