### ISSUE TITLE
JLoader::import does not properly build class names

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-platform#1725]
Reference http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29757 from the CMS 2.5 Issue Tracker.  Verifying this bug, I got the following results.  Note that this is using the current CMS 2.5 head with Platform 11.4, but the method in question is unchanged aside from one conversion of `dirname(__FILE__)` to `__DIR__`

Trying to `jimport('joomla.html.html.string')` gives me the following data:
Class: `JString`
Path to file: `/cms_root/libraries/joomla/html/html/string.php`

Testing further, I did `jimport('joomla.image.filters.brightness')` to get JImageFilterBrightness:
Class: `JBrightness`
Path to file: `/cms_root/libraries/joomla/image/filters/brightness.php`

And lastly, a class that is loaded via the autoloader, JGithubForks via `jimport('joomla.github.forks')`
Class: `JForks`
Path to file: `/cms_root/libraries/joomla/github/forks.php`

**Comment by dongilbert** [comment]
Sure is a bug. Looking at the code it's clear what's going on, and it's obviously wrong. It just takes the last part of import $key and then prepends J (unless it's a helper class).

A lot more thinking needs to be done on this than what I can offer right now (it's 12:25 am). There's really a fundamental issue here, since not all class names follow the Joomla Namespace / Folder structure. There would need to be quite a few special cases coded for things like the image filters as well as the JHtml sub classes (since in those situations the class names don't follow folder structure.)

The solution MAY be to build an config array that maps everything out. Each classname to the file it comes from, and then when you jimport, it searches that array first to see if it has a matching key, and if so, include the file.

**Comment by pasamio** [comment]
I think you're forgetting this is how we used to do things before we changed to using the autoloader to start shifting towards. JAuthentication in the current tree still follows this convention:
https://github.com/joomla/joomla-platform/blob/master/libraries/joomla/user/authentication.php

You would be doing a `jimport('joomla.user.authentication')` to get to the file loaded properly. This is before the camel case autoloader support was added and dates back to 1.5 era. For anything since then you should be using the autoloader and not using jimport (remember jimport is just short hand for JLoader::import). Look back to an older copy of Joomla and you will see this is working as intended.

**Comment by dongilbert** [comment]
Right, but we aren't ON an older version of Joomla anymore. And while
autoloading everything would be nice, we aren't to that point yet with the
class naming structure.

So, we can ignore this since we're (hopefully, at least I am) pushing for
full proper namespacing in Platform 13.2, which I hope would also see the
deprecation of JLoader::import - or we can fix it for the current version
of the platform.

**Comment by pasamio** [comment]
Once we're on autoloading then this function becomes deprecated and isn't necessary any more. We may not be on those older versions, but the function is behaving as expected for those existing classes that aren't following the autoloader. The JHtml stuff was never run through jimport (it loaded things itself) and the JImage/JGitHub stuff likely is new enough to have always used the autoloader.

So not a bug but expected behaviour.
