### ISSUE TITLE
User access levels cache not updated when user added to a new group (Joomla issue tracker id=26420)

### ISSUE THREAD

**Issue by jmcameron** [joomla/joomla-platform#245]
(from http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=26420)
## Test Instructions:
1. Log in back end as admin/super-user 
2. Create a new test group and corresponding access level derived from 'Registered' (do not add Super-user to the new access level). 
3. For debug output, edit libraries/joomla/user/user.php and add the following line of debug code to line 357 (after first 'if' statement in getAuthorizedViewLevels() function): echo "USERLEVELS: ".implode(',', $this->_authLevels)."<br/>"; 
4. Edit an article and notice the lists of access levels permitted. Cancel editing. 
5. Edit the admin/super-user account and make it a member of the new test group. Save. 
6. Edit an article again and notice that you are not in the new access level. 
7. Log out and log back in. Edit an article and notice that NOW the new test access level has been added to the list. 
8. Don't forget to remove the debugging code!
## Summary

user access levels cache not updated when user added to a new group
## Details

When a user is edited and is the groups that they are in are changed so that thier viewing access levels change, the cache in the user object is not invalidated or updated.   Only logging out and logging back in will force that change.   This could be very confusing since you expect to see changes you make to membership, etc, take place immediately.

Note: Elin Waring said that is cache-refresh problem is also an issue when a user changes their timezone.  In order for it to take effect, you must log out and log back in.  I have seen this issue as well.

**Comment by aaronschmitz** [comment]
@elinw, I can work on this one, but I'm going to need some guidance - it's a bit over my head.

**Comment by elinw** [comment]
Ok, check for me tonight or tomorrow on IRC and we can look at it.

**Comment by jmcameron** [comment]
Hi Elin and Aaron,

I'm willing to help out with this issue.  I've been preoccupied on other
things and have neglected it.

I started getting set up with a fresh git checkout of the platform, etc, to
try get this patch fixed.

I'm tied up this evening and tomorrow morning (Pacific time).   Maybe we
can touch base tomorrow afternoon/evening?

-Jonathan

On Fri, Mar 30, 2012 at 4:58 AM, elinw <
reply@reply.github.com

**Comment by elinw** [comment]
ok will look for you

**Comment by jmcameron** [comment]
Ok, sorry I did not connect earlier.  I will not be able to follow up on this any time soon.  So I encourage you both to take it over and follow it up.

**Comment by aaronschmitz** [comment]
@elinw, I seem to be running into a problem on this bug. I want to do something as simple as    "$session = JFactory::getSession(); $session->set('user', $this);," but this simply modifies the session of the currently logged in user - not the user we are changing. I need to find every session matching the username/id of the user we are changing and update those rows. Unfortunately, the abstract class that all the different types of session stores implement only has the ability to open, close, read, and write sessions by session ID. There's seemingly no way to get a list of sessions to pick out the appropriate ones.

http://docs.joomla.org/API15:JSessionStorage

**Comment by elinw** [comment]
If users are changing their own, it's working as expected is that right?

**Comment by AmyStephen** [comment]
@aaronschmitz In Joomla, the User session namespace is used for the current logged on user. It's created in JFactory https://github.com/joomla/joomla-platform/blob/staging/libraries/joomla/factory.php#L213
- When the administrator is logged on changing ACL data, it is that person's data stored in the user object. 

What you want to do is force an update for the User session namespace for the visitor _whose ACL data was changed._  So, you have to try to make that happen for that user during their next page load.

Which means you have to create some kind of indicator that is used by Joomla when the visitor makes their next request that signals it is time tto refresh their JUser Object (and therefore update their Session data). 

How you do that is probably something that the Platform Team will be interested in discussing since it could be a performance issue. 
- Maybe you can update the Users Session table row? (I would be very nervous about that.) 
- Maybe a check can be made to see if the user's last updated date on their user record is after their last visit date (and if so, refresh the JUser object -- without forcing a logon).

Sessions are always very tricky, will be good to see what @LouisLandry or @eddieajau think about a best approach or even if it's a viable option.

**Comment by aaronschmitz** [comment]
@AmyStephen, ok. That basically mirrors the only solution I could come up with, so I'm glad we're on the same page. I was hoping there was an easier solution, but due to technical limitations my best idea was to add a lastChange column with a timestamp to the users table and force the session row to be updated on the next page hit by the user if it's older than the timestamp.

**Comment by AmyStephen** [comment]
@aaronschmitz - re-read your comment. I kind of doubt the Platform team will want to add a column to the table for this. Wonder if you can do something with the time column -- set it to spaces, or something, and use that to prompt the refresh? Maybe look at the Application checkSession method and see what you can do there.

**Comment by aaronschmitz** [comment]
@AmyStephen, I'm aware. However, we need a timestamp - not a mere flag - because, as I understand, any given user could have multiple sessions. If we use a flag, we would only be able to refresh the first.

**Comment by AmyStephen** [comment]
@aaronschmitz Users have one session per application. The approach I suggested could be used to prompt each application session to refresh, as you are rightly indicated is needed.

You can try a new field, I'm just saying I am not certain it will be viewed as worthwhile considering the 'cost' of the change (upgrading the table and migrations are complicated with DDL changes.) If there is a way to do this without changing the DDL, it will make your proposal easier to accept, IMO. (I don't get to choose, it's just my observation.)

**Comment by aaronschmitz** [comment]
@AmyStephen, I mean if a user is logged in on two different browsers.
https://lh4.googleusercontent.com/-7fcLrOPB8lI/T3swz1it2rI/AAAAAAAAAKs/oE99YnrKASg/s800/Capture2.PNG

... and as a core developer at LimeSurvey, I know how much work it is to push a schema change, unfortunately.

**Comment by AmyStephen** [comment]
@aaronschmitz OK, but still trying to understand why that means there needs to be a new column added.  Wouldn't  you simply update all rows for a user whether you use the existing time column or a new column? In either case, all sessions would need to be updated - and each could be since the related data for that session would have a hook.

If (session time == '') {
do a refresh;
}
- or -

if (session time earlier than new column) {
do a refresh;
}

Same thing?

**Comment by aaronschmitz** [comment]
No. When you run that code, if you set session time to '' and don't set it back, sessions will always be reloaded which totally defeats the purpose of the cache. On the other hand, if you reset the session time to the current time when you update one of the session rows, you will inevitably fail to update the second session row if one exists.

**Comment by AmyStephen** [comment]
@aaronschmitz - You would have to write a little code to handle logic for a new column, right? My point to you is you _could_ modify the code to respond to different values in an _existing_ column. 

Lots of ways to do this. In the end, what the maintainers are willing to accept is really all that matters. Since I am not a maintainer, and since you are now approaching this from the right "side" -- this will be my last response.

Thanks for taking time to make Joomla better.

**Comment by eddieajau** [comment]
I know I said to post this issue here, but in hindsight it's not something that is specifically for the platform to fix (in other words, it's still part of the coupling we want to get rid of).  I'm pretty sure there is an easy workaround in com_users but I've just never had the time to look at it despite the fact it annoys the life out of me.
