### ISSUE TITLE
JRules() abandoned with no backward compatibility

### ISSUE THREAD

**Issue by tomfuller2** [joomla/joomla-platform#725]
In Joomla 1.7.3: administrator/com_config/models/component.php on line 119:

$rules  = new JRules($data['params']['rules']);

Same file in Joomla 2.5 beta 1 on line 116:

$rules  = new JAccessRules($data['params']['rules']);

If you try to use JRules() in a component running under 2.5 you get a fatal
error.

The main problem for 3rd party developers is that a component cannot run under
1.7 and 2.5 because the class has changed with no backward compatibility.

See here for bug on JoomlaCode with link to a component you can try this on. Under 2.5 you cannot save any records.
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=27656

Also see this discussion for possible solutions:
https://groups.google.com/forum/?hl=en#!topic/joomla-dev-general/y3DbsiIPtp4

**Comment by realityking** [comment]
This was fixed on the CMS side. There actually is a proxy that allows you to keep using the name JRules (for now)

The problem was that extensions didn't import all the classes they used but relied on other classes importing them. When those imports were removed because of the autoloading stuff started breaking.
