### ISSUE TITLE
Code not needed on platform

### ISSUE THREAD

**Issue by fastslack** [joomla/joomla-platform#817]
This code is needed on platform?

99cdf85712fabb90c1c5958c1e317a37ee1847db

**Comment by eddieajau** [comment]
The whole menu table is not required on the platform.  Most, possibly all, can move to the /cms/ tree.

**Comment by fastslack** [comment]
In the future.. we will be able to use the cms tables from cli?

**Comment by eddieajau** [comment]
They will be moved to the CMS, so you can grab a copy from there, but they won't be specifically in the platform.

**Comment by fastslack** [comment]
I have opened a pull request with this patch: 85739da04aa15fa0abbc83cd417ed0b922f69658

This patch will be applied? Will probably also beneficial to the cms

**Comment by elinw** [comment]
IT's actually quite important that you not allow the first level name to be a folder because that will keep webmasters from being able to install another application on their domain in  a subfolder. You could say it is a bit paternalistic in preventing users from making mistakes but we know on the cms side that we get many but reports that are related to the user error of having the matching alias.

**Comment by LouisLandry** [comment]
This appears to be all tidied up so I'm closing it.  Thanks a bunch @fastslack
