### ISSUE TITLE
Installer removes media/{folder} even it is not empty & used by another extension

### ISSUE THREAD

**Issue by Svel** [joomla/joomla-platform#820]
Installer removes media/{folder} even it is not empty & used by another extension.

In [libraries/joomla/installer/installer.php](https://github.com/joomla/joomla-platform/blob/143427ab73edbaed0da80e77cce60c294ae7e3a9/libraries/joomla/installer/installer.php#L1790).

**Comment by elinw** [comment]
I don't see how the installer can know that another extension is using a folder that specifically belongs to an extension. Having other extensions use the same folder seems like a very dangerous practice for just this reason.

Compare with #287 there seems to be some debate about proper  behavior.

**Comment by LouisLandry** [comment]
It is expected behavior that the installer remove media folders that it creates during an uninstall.  If you are looking for some sort of additional feature to allow the installer a flag to choose not removing a media path, then you should submit that to the CMS feature tracker.  The installation libraries, while they exist in the platform today, are being relocated into the CMS repository because they are very CMS specific as they are built now.

Thanks!
